import type { Metadata } from "next"
import { Krub } from "next/font/google"
import "./globals.css"
import Wrapper from "../components/Wrapper"
import "./embla.css"
import { BreadcrumbsProvider } from "@/contexts/useBreadcrumbs"
import { UserProvider } from "@/contexts/useUser"
const krub = Krub({
  variable: "--font-krub",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap", // Ensures text is displayed while the font is loading
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" />
      </head>
      <body className={`${krub.variable} antialiased`}>
        <BreadcrumbsProvider>
          <UserProvider>
            <Wrapper>{children}</Wrapper>
          </UserProvider>
        </BreadcrumbsProvider>
      </body>
    </html>
  )
}
